[[redirects]]
from = "/play"
to = "/index.html"
status = 200

[[redirects]]
from = "/join"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "https://api-fb6o.onrender.com"
status = 200